#!/usr/bin/env python3 

import os, sys, shutil

# get absolute input and output paths
input_path = os.path.join(
    os.getenv('MESON_BUILD_ROOT'), 
    'compile_commands.json')

output_path = os.path.join(
    os.getenv('MESON_SOURCE_ROOT'), 
    'compile_commands.json')

# and finally copy the file
try:
    shutil.copyfile(input_path, output_path)
except:
    print("Copying compilation database failed")
